config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    member do
      patch :update_role
    end
  end

  root 'home#index'
  resources :notes

  get 'home/dashboard', to: 'home#dashboard', as: 'dashboard'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    user.role ||= 'reader'

    can :manage, :all if user.admin?

    return unless user.reader?

    can :read, Note
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, :text, presence: true

  scope :with_longest_text, lambda {
    order("LENGTH(text) DESC").limit(1)
  }

  def self.average_word_count(total_notes)
    total_words = Note.pluck(:text).sum { |text| text.split.size }
    total_notes.zero? ? 0 : total_words / total_notes.to_f
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy

  validates :name, :last_name, presence: true

  enum role: { reader: 'reader', admin: 'admin' }

  scope :with_most_notes, lambda {
    joins(:notes)
      .group(:id)
      .order("COUNT(notes.id) DESC")
      .limit(1)
  }

  def self.average_notes_per_user(total_users)
    return 0 if total_users.zero?

    joins(:notes)
      .group('users.id')
      .count
      .values
      .sum / total_users.to_f
  end

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, alert: I18n.t('errors.access_denied')
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  before_action :redirect_if_logged_in, only: [:index]

  def index; end

  def dashboard
    authorize! :read, :dashboard

    set_user_data
    set_average_metrics
  end

  private

  def redirect_if_logged_in
    return unless user_signed_in?

    redirect_to(current_user.admin? ? dashboard_path : notes_path)
  end

  def set_average_metrics
    @average_notes_per_user = User.average_notes_per_user(@total_users).round(2)
    @average_words_per_note = Note.average_word_count(@total_notes).round(2)
  end

  def set_user_data
    @total_users = User.count
    @total_notes = Note.count

    @user_with_most_notes = User.with_most_notes.first.full_name
    @user_with_longest_note = Note.with_longest_text.first.user.full_name
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @notes = current_user.admin? ? current_user.notes : Note.all
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def edit
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: I18n.t('notices.note.created')
    else
      render 'new'
    end
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: I18n.t('notices.note.updated')
    else
      render 'edit'
    end
  end

  def destroy
    if @note.destroy
      redirect_to notes_path, notice: I18n.t('notices.note.destroyed')
    else
      redirect_to notes_path, alert: I18n.t('alerts.note.destroy_error')
    end
  end

  private

  def find_note
    @note = if current_user.admin?
              current_user.notes.find_by(id: params[:id])
            else
              Note.find_by(id: params[:id])
            end

    redirect_to notes_path, alert: I18n.t('alerts.note.not_found') unless @note
  end

  def note_params
    params.require(:note).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def update_role
    user = User.find(params[:id])
    if user.update(role: params[:user][:role])
      redirect_to user.admin? ? users_path : root_path, notice: I18n.t('notices.user.role_updated')
    else
      redirect_to users_path, alerts: I18n.t('notices.user.update_failed')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def style_for_flash(type)
    case type.to_sym
    when :notice
      'bg-blue-100 border-l-4 border-blue-500 text-blue-700'
    when :alert
      'bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700'
    when :error
      'bg-red-100 border-l-4 border-red-500 text-red-700'
    else
      ''
    end
  end
end

app/views/home/dashboard.html.haml
%div.min-h-screen.p-6
  %div.max-w-6xl.ml-8
    %div.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.gap-6.mt-20
      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2  Total users
        %p.text-3xl.font-bold.text-indigo-600= @total_users

      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2 Total notes
        %p.text-3xl.font-bold.text-indigo-600= @total_notes

      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2  Average notes per user
        %p.text-3xl.font-bold.text-indigo-600= @average_notes_per_user

      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2  Average words per note
        %p.text-3xl.font-bold.text-indigo-600= @average_words_per_note

      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2  User with Most Notes
        %p.text-3xl.font-bold.text-indigo-600=@user_with_most_notes

      %div.bg-white.shadow-xl.rounded-lg.p-6
        %h3.text-lg.font-semibold.text-gray-800.pb-2  User with Longest Note
        %p.text-3xl.font-bold.text-indigo-600=@user_with_longest_note

app/views/home/index.html.haml
%div.min-h-screen.bg-gray-100.flex.items-center.justify-center
  %div.text-center.bg-white.shadow-lg.rounded-lg.p-8.max-w-md
    %h1.text-4xl.font-extrabold.text-gray-800.mb-4 QuickNotes
    %p.text-lg.text-gray-600.mb-6 Your personal note-taking app with role-based access.
    %p.mt-4.text-gray-500
      Already have an account?
      = link_to 'Sign in here', new_user_session_path, class: 'text-blue-500 hover:text-blue-600'
    %p.mt-4.text-gray-500
      Don't have an account?
      = link_to 'Sign up here', new_user_registration_path, class: 'text-blue-500 hover:text-blue-600'

app/views/layouts/_navbar.html.haml
%nav.bg-purple-50.px-4.py-6.fixed.top-0.left-0.h-full.z-10.shadow-md
  %div.flex.flex-col.items-start.space-y-6
    %div.flex.items-center.space-x-3
      = link_to image_tag("notes-logo.svg", alt: "Logo", class: "h-12"), root_path
      %span.text-gray-800.text-xl.font-semibold QuickNotes

    %div.text-gray-600.mt-2
      %span.block.text-sm Welcome, #{current_user.name}!

    %div.flex-grow.flex.flex-col.space-y-4.mt-6
      - if can? :manage, :all
        %div.flex.flex-col.space-y-4
          %div.flex.items-center.space-x-3
            %span.text-gray-700.font-semibold Manage Notes

          %div.flex.flex-col.space-y-3.ml-6
            %div.flex.items-center.space-x-3
              %i.fas.fa-plus-circle.text-gray-600
              = link_to 'Create New Note', new_note_path, class: "text-gray-600 hover:text-indigo-500 font-semibold"

            %div.flex.items-center.space-x-3
              %i.fas.fa-eye.text-gray-600
              = link_to 'My Notes', notes_path, class: "text-gray-600 hover:text-indigo-500 font-semibold"

          %div.flex.items-center.space-x-3
            %i.fas.fa-users.text-gray-600
            = link_to 'User Management', users_path, class: "text-gray-600 hover:text-indigo-500 font-semibold"

      - elsif can? :read, Note
        %div.flex.items-center.space-x-3
          %i.fas.fa-eye.text-gray-600
          = link_to 'View All Notes', notes_path, class: "text-gray-600 hover:text-indigo-500 font-semibold"

    %div.text-gray-600.mt-auto
      %div.flex.items-center.space-x-3
        %i.fas.fa-sign-out-alt.text-gray-600
        = link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-gray-600 hover:text-indigo-500 font-semibold"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NotesChallenge
    %meta{content: "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    - if user_signed_in?
      .flex
        .w-64.text-white.p-4.fixed.left-0.top-0.h-screen
          = render 'layouts/navbar'
        .ml-64.flex-1.p-4
          = render 'shared/flash_messages'
          = yield
    - else
      .flex
        .w-full
          = render 'shared/flash_messages'
          = yield

app/views/notes/_form.html.haml
%div.mt-5
  = form_with model: note, local: true, data: { turbo: false } do |f|
    - if note.errors.any?
      %div.bg-red-100.border-l-4.border-red-500.text-red-700.p-4.mb-4
        %ul
          - note.errors.full_messages.each do |msg|
            %li= msg
    .mb-4
      = f.label :title, "Title", class: "form-label"
      = f.text_field :title, autofocus: true, class: "form-input"
    .mb-4
      = f.label :text, "Text", class: "form-label"
      = f.text_area :text, class: "form-input h-96"
    .mb-6
      = f.submit "Save", class: "form-button"

app/views/notes/edit.html.haml
%div.min-h-screen.p-6
  %div.max-w-3xl.mt-10
    %h1 Edit Note

    = render 'form', note: @note

app/views/notes/index.html.haml
.div.min-h-screen.p-6
  %div.max-w-6xl.mt-10
    %h2.text-2xl.font-semibold.mb-4 Notes

    - if @notes.blank?
      %p.text-gray-500 No notes available.
    - else
      .overflow-x-auto
        %table.min-w-full.table-auto.border-collapse.border.border-gray-300.text-sm
          %thead.bg-gray-100
            %tr
              %th.px-4.py-2.border.border-gray-300.text-left Title
              %th.px-4.py-2.border.border-gray-300.text-left Text
              %th.px-4.py-2.border.border-gray-300.text-left Actions
          %tbody
            - @notes.each do |note|
              %tr.border-t.border-gray-200
                %td.px-4.py-2.border.border-gray-300= note.title
                %td.px-4.py-2.border.border-gray-300= note.text.truncate(200)
                %td.px-4.py-2.flex.justify-center.items-center
                  - if can? :manage, :all
                    = link_to note_path(note), class: "inline-block p-2 rounded-full opacity-80" do
                      %i.fas.fa-eye.h-6.w-6
                    = link_to edit_note_path(note), class: "inline-block p-2 rounded-full opacity-80" do
                      %i.fas.fa-edit.h-6.w-6
                    = button_to note_path(note), method: :delete, data: { confirm: "Are you sure?" }, class: "inline-block p-2 rounded-full opacity-80", id: "delete-button-#{note.id}" do
                      %i.fas.fa-trash.h-6.w-6
                  - elsif can? :read, Note
                    = link_to note_path(note), class: "inline-block p-2 rounded-full opacity-80" do
                      %i.fas.fa-eye.h-6.w-6s

app/views/notes/new.html.haml
%div.min-h-screen.p-6
  %div.max-w-3xl.mt-10
    %h1 Add Note

    = render 'form', note: @note

app/views/notes/show.html.haml
%div.min-h-screen.p-6
  %div.max-w-3xl.mt-10.bg-white.shadow-lg.rounded-lg.p-6
    #note_show
      %h1.text-3xl.font-bold.text-gray-800.mb-4= @note.title
      %p.text-gray-700.leading-relaxed.mb-6= simple_format(@note.text)

      -if can? :manage, :all
        .buttons.flex.justify-between.mt-4
          = button_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-700 text-white font-semibold py-2 px-10 rounded-lg shadow-md", id: "delete-button-#{@note.id}"
          = link_to "Edit", edit_note_path(@note), class: "bg-gray-500 hover:bg-gray-700 text-white font-semibold  py-2 px-10 rounded-lg shadow-md"

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  - next unless ['notice', 'alert', 'error'].include? type.to_s
  %div.flash-message{class: "fixed top-4 right-4 p-4 max-w-xs rounded-lg shadow-lg #{style_for_flash(type)} transition-opacity duration-500 opacity-100"}
    %p= message

app/views/users/index.html.haml
%div.container.mx-auto.py-10
  %h1.text-2xl.font-bold.text-gray-800.mb-6 User Management

  %table{class: "w-1/2 table-auto border-collapse border border-gray-300 text-sm"}
    %thead.bg-gray-200
      %tr
        %th.border.border-gray-300.px-4.py-2.text-left Name
        %th.border.border-gray-300.px-4.py-2.text-left Email
        %th.border.border-gray-300.px-4.py-2.text-left Role

    %tbody
      - @users.each do |user|
        %tr{id: "user_#{user.id}"}
          %td.border.border-gray-300.px-4.py-2= user.name
          %td.border.border-gray-300.px-4.py-2= user.email
          %td.border.border-gray-300.px-4.py-2
            = form_with model: user, url: update_role_user_path(user), method: :patch, local: true, data: { turbo: false } do |f|
              %div.flex.items-center.space-x-4
                %label.flex.items-center.space-x-2
                  = f.radio_button :role, 'reader', checked: user.reader?
                  %span Reader
                %label.flex.items-center.space-x-2
                  = f.radio_button :role, 'admin', checked: user.admin?
                  %span Admin
                = f.submit 'Save', class: "bg-blue-400 text-white px-6 py-2 rounded text-sm"